### ISSUE TITLE
Update/delete refDocs

### ISSUE THREAD

**Issue by mreis92** [fogine/couchbase-odm#17] opened 2016-08-29 07:46 UTC
Hello! In the following model, I was wondering if it is possible to create a refDoc after a model is created:

```
var User = couchbase.define('User',
    {
        type: DataTypes.HASH_TABLE,
        schema: {
            name: { type: DataTypes.STRING },
            facebookId: { type: DataTypes.STRING, allowEmptyValue: true },
	},
	{
		indexes: {
			refDocs: {
				getByFacebookId: {
					keys: ['facebookId'],
					required: false
				}
			}
		},
	}
);
```

Succinctly, I can create a model without a facebookId, but later on in time I may want to add an index using this field. Right now, when I try to this, an error is thrown. Is this the expected behavior? Let me know if you need more information

**Comment by fogine** [comment] 2016-08-29 12:26
Hello @mreis92 ,

thank you for the bug report! I believe that this is duplicate of the #15 so I'm gonna close this issue. Feel free to reopen if the issue still persists.

**Closed by fogine** 2016-08-29 12:26 UTC
